const Colors = {
  mintGreen: '#A8E6CF',
  mintGreenDark: '#6BBF9A',
  mintGreenLight: '#C8F0E3',
  peachPink: '#FFD3B6',
  peachPinkDark: '#FFBA8C',
  peachPinkLight: '#FFE8D9',
  skyBlue: '#C7CEEA',
  skyBlueDark: '#A3ACD4',
  skyBlueLight: '#E3E7F5',
  creamBeige: '#E0F2E9',
  creamBeigeDark: '#C8E6D5',
  goldAccent: '#6BBF9A',
  goldAccentLight: '#C8F0E3',
  background: '#F8FEFA',
  backgroundSecondary: '#F0FAF4',
  cardBackground: '#FFFFFF',
  textPrimary: '#333333',
  textSecondary: '#636E72',
  textMuted: '#B2BEC3',
  white: '#FFFFFF',
  danger: '#FF6B6B',
  dangerLight: '#FFE0E0',
  shadow: '#2D3436',
  light: {
    text: '#333333',
    background: '#F8FEFA',
    tint: '#A8E6CF',
    tabIconDefault: '#B2BEC3',
    tabIconSelected: '#A8E6CF',
  },
};

export default Colors;
