const AVATAR_MAP: Record<string, any> = {
  'assets/avatars/boy01.png': require('../assets/avatars/boy01.png'),
  'assets/avatars/boy02.png': require('../assets/avatars/boy02.png'),
  'assets/avatars/boy03.png': require('../assets/avatars/boy03.png'),
  'assets/avatars/boy04.png': require('../assets/avatars/boy04.png'),
  'assets/avatars/boy05.png': require('../assets/avatars/boy05.png'),
  'assets/avatars/boy06.png': require('../assets/avatars/boy06.png'),
  'assets/avatars/boy07.png': require('../assets/avatars/boy07.png'),
  'assets/avatars/boy08.png': require('../assets/avatars/boy08.png'),
  'assets/avatars/boy09.png': require('../assets/avatars/boy09.png'),
  'assets/avatars/boy10.png': require('../assets/avatars/boy10.png'),
  'assets/avatars/boy11.png': require('../assets/avatars/boy11.png'),
  'assets/avatars/boy12.png': require('../assets/avatars/boy12.png'),
  'assets/avatars/boy13.png': require('../assets/avatars/boy13.png'),
  'assets/avatars/boy14.png': require('../assets/avatars/boy14.png'),
  'assets/avatars/boy15.png': require('../assets/avatars/boy15.png'),
  'assets/avatars/boy16.png': require('../assets/avatars/boy16.png'),
  'assets/avatars/boy17.png': require('../assets/avatars/boy17.png'),
  'assets/avatars/boy18.png': require('../assets/avatars/boy18.png'),
  'assets/avatars/boy19.png': require('../assets/avatars/boy19.png'),
  'assets/avatars/boy20.png': require('../assets/avatars/boy20.png'),
  'assets/avatars/boy21.png': require('../assets/avatars/boy21.png'),
  'assets/avatars/boy22.png': require('../assets/avatars/boy22.png'),
  'assets/avatars/boy23.png': require('../assets/avatars/boy23.png'),
  'assets/avatars/boy24.png': require('../assets/avatars/boy24.png'),
  'assets/avatars/boy25.png': require('../assets/avatars/boy25.png'),
  'assets/avatars/boy26.png': require('../assets/avatars/boy26.png'),
  'assets/avatars/boy27.png': require('../assets/avatars/boy27.png'),
  'assets/avatars/boy28.png': require('../assets/avatars/boy28.png'),
  'assets/avatars/boy29.png': require('../assets/avatars/boy29.png'),
  'assets/avatars/boy30.png': require('../assets/avatars/boy30.png'),
  'assets/avatars/boy31.png': require('../assets/avatars/boy31.png'),
  'assets/avatars/boy32.png': require('../assets/avatars/boy32.png'),
  'assets/avatars/boy33.png': require('../assets/avatars/boy33.png'),
  'assets/avatars/boy34.png': require('../assets/avatars/boy34.png'),
  'assets/avatars/boy35.png': require('../assets/avatars/boy35.png'),
  'assets/avatars/girl01.png': require('../assets/avatars/girl01.png'),
  'assets/avatars/girl02.png': require('../assets/avatars/girl02.png'),
  'assets/avatars/girl03.png': require('../assets/avatars/girl03.png'),
  'assets/avatars/girl04.png': require('../assets/avatars/girl04.png'),
  'assets/avatars/girl05.png': require('../assets/avatars/girl05.png'),
  'assets/avatars/girl06.png': require('../assets/avatars/girl06.png'),
  'assets/avatars/girl07.png': require('../assets/avatars/girl07.png'),
  'assets/avatars/girl08.png': require('../assets/avatars/girl08.png'),
  'assets/avatars/girl09.png': require('../assets/avatars/girl09.png'),
  'assets/avatars/girl10.png': require('../assets/avatars/girl10.png'),
  'assets/avatars/girl11.png': require('../assets/avatars/girl11.png'),
  'assets/avatars/girl12.png': require('../assets/avatars/girl12.png'),
  'assets/avatars/girl13.png': require('../assets/avatars/girl13.png'),
  'assets/avatars/girl14.png': require('../assets/avatars/girl14.png'),
  'assets/avatars/girl15.png': require('../assets/avatars/girl15.png'),
  'assets/avatars/girl16.png': require('../assets/avatars/girl16.png'),
  'assets/avatars/girl17.png': require('../assets/avatars/girl17.png'),
  'assets/avatars/girl18.png': require('../assets/avatars/girl18.png'),
  'assets/avatars/girl19.png': require('../assets/avatars/girl19.png'),
  'assets/avatars/girl20.png': require('../assets/avatars/girl20.png'),
  'assets/avatars/girl21.png': require('../assets/avatars/girl21.png'),
  'assets/avatars/girl22.png': require('../assets/avatars/girl22.png'),
  'assets/avatars/girl23.png': require('../assets/avatars/girl23.png'),
  'assets/avatars/girl24.png': require('../assets/avatars/girl24.png'),
  'assets/avatars/girl25.png': require('../assets/avatars/girl25.png'),
  'assets/avatars/girl26.png': require('../assets/avatars/girl26.png'),
  'assets/avatars/girl27.png': require('../assets/avatars/girl27.png'),
  'assets/avatars/girl28.png': require('../assets/avatars/girl28.png'),
  'assets/avatars/girl29.png': require('../assets/avatars/girl29.png'),
  'assets/avatars/girl30.png': require('../assets/avatars/girl30.png'),
  'assets/avatars/girl31.png': require('../assets/avatars/girl31.png'),
  'assets/avatars/girl32.png': require('../assets/avatars/girl32.png'),
  'assets/avatars/girl33.png': require('../assets/avatars/girl33.png'),
  'assets/avatars/girl34.png': require('../assets/avatars/girl34.png'),
  'assets/avatars/girl35.png': require('../assets/avatars/girl35.png'),
};

export const BOY_AVATARS = Array.from({ length: 35 }, (_, i) => `assets/avatars/boy${String(i + 1).padStart(2, '0')}.png`);

export const GIRL_AVATARS = Array.from({ length: 35 }, (_, i) => `assets/avatars/girl${String(i + 1).padStart(2, '0')}.png`);

export function getAvatarSource(path: string): any {
  return AVATAR_MAP[path] || null;
}

export default AVATAR_MAP;
